### ISSUE TITLE
REVAD-bot仕様

### ISSUE THREAD

**Issue by Ikuyadeu** [OSSresearch-SuperTeam/REVAD-bot#1]
REVAD-botの仕様についての決定事項

# 計画項目
| マーク | 詳細 |
|:--|:--|
🏃  | 進行中 |
✋  | 中断中 |
💪 | 優先的 |
🔵 | 要詳細 |

* [ ] 目的
* [ ] 機能
  * [ ] 提出したソースコードはすでに投稿されていないかを確認 
  * [ ]  ソースコードを投稿したときに，怪しい箇所を特定 
  * [ ] レビューアの推薦 
  * [ ] レビューコメントの修正を提案

**Comment by akinori-i** [comment]
最終的には自動コードレビューができたら良いと思っています．
さすがに初めから自動コードレビューはできないので，まずはすでに研究が始ているレビューのアサイメント，レビュー時間予測，採択/不採択予測，レビューア合意形成のところを支援する研究を実装できるのが良いかと思っています．

また，初めからGerritに実装というのも難しいのではないかと心配していますがどうでしょう？

**Comment by Ikuyadeu** [comment]
1. 一部機能の作成
2. botに実装
の繰り返しでしたら、一部ならできそうかと思います。
GitHubでなくGerritの理由はなんでしょうか？

**Comment by akinori-i** [comment]
1. 一部機能の作成 -> 賛成です．まずは既存の研究を実装する感じでいいと思います
2. Githubでいいと思います．ソフトウェア工学でGerritを使ったコードレビューの研究が多く使われているで言っただけです．

実装する上で，すでに運用中のプロジェクトをケーススタディとして使わないと難しいでしょうか？

**Comment by Ikuyadeu** [comment]
わかりました。

そうですよね、すでにbotが動いているプロジェクトでのbotの信頼度と作成したbotが仮に動いた場合の信頼度は比較したいですね。

**Comment by akinori-i** [comment]
もしケーススタディのプロジェクトがなければ，ちょっと異色ですが，私の研究グループでgithubを使って論文管理をしているので，それをケーススタディとできないですかね？？w

**Comment by Ikuyadeu** [comment]
https://github.com/Microsoft/vscode/pull
これなんかですと、レビュアーを推薦するmention-botと認証を受けた開発者を判断するmsftclasが動いているみたいです。

**Comment by akinori-i** [comment]
おお！すごいですね！ここまで使っていただけるといいですが，まずは難しいでしょうね．
もしこのプロジェクトのメンバが増えて．実装が進めば，このプロジェクトをケーススタディにできるんでしょうけど．．．

**Comment by Ikuyadeu** [comment]
PR情報をhttps://developer.github.com/v3/pulls/
ここらへんからとってきて
性能の比較をすることができませんか？

**Comment by akinori-i** [comment]
最終的にどっかのプロジェクトのデータを使うってことだよね？それは一言伝えておかないとトラブル起きた時に面倒じゃない？

**Comment by Ikuyadeu** [comment]
あ、そうですね。
それが許可されているプロジェクトを探さないといけないんですね。

**Comment by Ikuyadeu** [comment]
論文管理のプロジェクトは論文の内容のbotと比較でしょうか？
それともそのプロジェクトでbotを動かすということでしょうか？

**Comment by akinori-i** [comment]
そもそもプロジェクトでbotを動かすということです．クローズドにしているので，公開するときにはサンプルが必要になるかもしれませんが．もし見たければインバイトしますよ．

**Comment by Ikuyadeu** [comment]
はい、よろしくお願いします。

**Comment by akinori-i** [comment]
インバイトしました．とりあえず今はReadだけできるようにしています．

**Comment by akinori-i** [comment]
説明して欲しい感じだったらskype等で連絡してきて．
