### ISSUE TITLE
現状の問題点まとめ

### ISSUE THREAD

**Issue by Ikuyadeu** [OSSresearch-SuperTeam/REVAD-bot#4]
# 問題点
* 誤字脱字がチェックできない
* 編集者が独立しているためチェックが一人に偏る
* 似たドキュメントを書いている人を互いに認知できない

# botの目標
* 似たドキュメントを書いている開発者を特定
* 登録された開発者を推薦
* ~~誤字脱字チェック~~(CIの採用が妥当なので保留)
* issueの議論のまとめ

**Comment by akinori-i** [comment]
似たドキュメントを書いている人を互いに認知できないについては，ソフトウェア開発の重複提案: duplicate（同じ機能を持つパッチの開発を複数の人が提出している）を特定するのに使えそうですね！

p.s. 今週は国際会議出張でリプライが少し遅れそうです．．．

**Comment by Ikuyadeu** [comment]
botの稼働対象が変化したためClose
